/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.5/userguide/java_library_plugin.html
 */

val versions = mapOf("slf4j" to "1.7.25", "logback" to "1.2.3", "jackson" to "2.9.8",
                     "classgraph" to "4.8.87", "lombok" to "1.18.12", "junit" to "4.13")

plugins {
    `java-library`
}

repositories {
    mavenLocal()
    maven { url = uri("https://oss.sonatype.org/content/repositories/snapshots") }
    mavenCentral()
    jcenter()
}

group = "io.github.zero88"

dependencies {
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api("org.slf4j:slf4j-api:${versions["slf4j"]}")

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    compileOnly("ch.qos.logback:logback-classic:${versions["logback"]}")
    compileOnly("io.github.classgraph:classgraph:${versions["classgraph"]}")
    compileOnly("com.fasterxml.jackson.core:jackson-annotations:${versions["jackson"]}")
    compileOnly("org.projectlombok:lombok:${versions["lombok"]}")
    annotationProcessor("org.projectlombok:lombok:${versions["lombok"]}")

    testImplementation("junit:junit:${versions["junit"]}")
    testImplementation("ch.qos.logback:logback-classic:${versions["logback"]}")
    testCompileOnly("org.projectlombok:lombok:${versions["lombok"]}")
    testAnnotationProcessor("org.projectlombok:lombok:${versions["lombok"]}")
}